##################################################################################################
# Ingress Routing
##################################################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: {{.Values.ingress.metadata.name}}
 annotations:
  ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - 
  http:
    paths:
    - path: {{.Values.ingress.path}}
      backend:
        serviceName: {{.Values.ingress.serviceName}}
        servicePort: {{.Values.ingress.servicePort}}